### ISSUE TITLE
EnableAmendment/Simple.tsx should be translatable

### ISSUE THREAD

**Issue by tequdev** [ripple/explorer#1076]
https://github.com/ripple/explorer/blob/5a93a6d133a11b27968536811266261f475d9e99/src/containers/shared/components/Transaction/EnableAmendment/Simple.tsx#L59

like 
```tsx
<SimpleRow label={t("amendment_name")} data-test="name">
```

**Comment by achowdhry-ripple** [comment]
Resolved in https://github.com/ripple/explorer/pull/1084
