### ISSUE TITLE
Unable to see full URI for long NFT URI's

### ISSUE THREAD

**Issue by JST5000** [ripple/explorer#108]
Quoting @andrew-keig-nomena who posted this issue on March 28th in the xrpl.js repo here: https://github.com/XRPLF/xrpl.js/issues/1944

When viewing my transaction on [nft-devnet.xrpl.org](http://nft-devnet.xrpl.org/), I am not able to see the complete IPFS link. Also would it be possible to provide a link to IPFS from here.

Example below:

https://nft-devnet.xrpl.org/transactions/DB45197C3165450FC3A1035C5517E09D0724DC9CF461E18899D2D883AC6FD227

**Comment by mvadari** [comment]
The link is purposefully not provided, because that could be a potential security issue

**Comment by JST5000** [comment]
Not hyperlinking is fine, but this is about how the text just runs off the screen without any way to copy + paste it. 

If our goal is to not show the link at all, then we should have a better user interface to demonstrate that. (Ex. "URI Hidden for security") 

(Although I think that having a plaintext version of the link be fully visible would be better than hiding the URI entirely)

**Comment by ledhed2222** [comment]
Added to our board

**Comment by ckniffen** [comment]
fixed by #261
