### ISSUE TITLE
When there are no transactions in a ledger show tx count

### ISSUE THREAD

**Issue by ckniffen** [ripple/explorer#131]
Show transaction count of 0 when there are no transactions.  Currently it looks like something went wrong with the ledger.

This is typically seen on https://testnet.xrpl.org/.

![Screen Shot 2022-04-27 at 6 09 33 PM](https://user-images.githubusercontent.com/464895/165645916-794f4f0c-e60a-4927-950f-afe9c2d84da7.png)

**Comment by connorjchen** [comment]
https://github.com/ripple/explorer/pull/289
