### ISSUE TITLE
Link explorer source code from site

### ISSUE THREAD

**Issue by mDuo13** [ripple/explorer#173]
It would be helpful for the Explorer website to link back to this repo so that people who are interested in it can find the source code. Many open-source projects do this in the form of a GitHub Octocat icon that links to the source repo, for example https://github.com/ripple/explorer/ —preferably with a "title" attribute that says "Source Code" or something so that desktop users can get a little note by hovering their mouse over the icon.

**Comment by ckniffen** [comment]
@mDuo13 Would placing it under the contribute section in the footer make sense as well?

**Comment by ckniffen** [comment]
Completed by #311
