### ISSUE TITLE
Link failed transaction error messages to tec codes doc page

### ISSUE THREAD

**Issue by bugsbunnies** [ripple/explorer#190]
Currently when you clicked into a failed transaction in the explorer you get an error message with no context like this screenshot, but would be great if they can actually link you to the tec codes doc page https://xrpl.org/tec-codes.html#tec-codes (open in new tab) you can see your error message and the corresponding explanation, instead of Googling it.

<img width="655" alt="image" src="https://user-images.githubusercontent.com/39572746/178792879-fcc17be9-445a-43d2-a452-bbee0a791ab1.png">

Proposed (link to tec codes doc page)
<img width="655" alt="image" src="https://user-images.githubusercontent.com/39572746/178793813-15925d5f-1cfa-43a3-a9c5-642150725008.png">

Icon SVG (in gray, hex #939A9F)
![link](https://user-images.githubusercontent.com/39572746/178794103-da33834e-8097-461b-8765-8910f955393e.svg)

**Comment by pdp2121** [comment]
Thank you for addressing it! A new ticket has been initiated for this feature.

**Comment by mvadari** [comment]
It would also be great if the tec codes page could have a `#` link (not sure what they're actually called, but like a sub-link) that links to each of the actual codes on the page.
