### ISSUE TITLE
Upgrade to react-router@6

### ISSUE THREAD

**Issue by ckniffen** [ripple/explorer#209]
Several changes need to be made to upgrade to the latest React Router.

## Rewrite `<Link>` usage

Use function to dynamically build the to path.

### Problem

react-router@6 does not allow nested <Router> elements.  We are using a loop hole in v5 to specify a conditional basename on a child <Router> to force child <Link>s to dynamically include a sidechain’s url.

Ex. `<Link to="/network"/>` resolves to `<a href="/example.mysidechain.com/network">` because it is inside the nested `<Router basename="example.mysidechain.com">`.

### Design

Since we are already rewriting every place using<Link>we should implement a typed route system. 

```
const function build<T>(route: Route<T>, params: T) { 
  const basename = sidechainUrl ?? '';
  generatePath(
    `${basename}/${route.path}`,
    params
  )
}
```

### Inspiration

https://blog.codacy.com/migrating-to-react-typed-named-routes-react-router-typescript/ 

### Problem

In react-router@6 match and location are no longer auto populated when used in conjunction with a <Route>.  With the removal of withRouter there isn’t another way to populate them besides the dreaded prop drilling.

### Design

Leverage hooks like `useParams`, `useLocation`, and `useMatch`. This can be done before switching to v6.

### Components Affected

- `LedgersPage`: Ledegers/index.js
- `Ledger`: Ledger/index.js
- `Transaction`: Transactions/index.js
- `Network`: Network/index.js
- `Validator`: Validators/index.js
- `PayString`: PayString/index.js
- `Token`: Token/index.js
- `NoMatch`: NoMatch/index.js

### Components Affected

- `App`: App/App.js
- `Search`: Header/Search.jsx

## Combine `AppWrapper` and `App`

There is no need to separate them now that nested Routers aren't required and most of its logic revolves around that.

### Design

Update App/index.js to be just an import point. Move logic into App/App.jsx.  Bonus points if we switch it to Typescript.

**Comment by ckniffen** [comment]
created https://github.com/ripple/explorer/tree/feature/better-routes and https://github.com/ripple/explorer/tree/feature/better-routes-with-router-6

**Comment by mvadari** [comment]
> Update App/index.js to be just an import point. Move logic into App/App.jsx. Bonus points if we switch it to Typescript.

The reason I didn't do this when adding the nested router logic was because the git history would have been removed.

**Comment by ckniffen** [comment]
> > Update App/index.js to be just an import point. Move logic into App/App.jsx. Bonus points if we switch it to Typescript.
> 
> The reason I didn't do this when adding the nested router logic was because the git history would have been removed.

Outlets did not exist in react-router@5 either.
