### ISSUE TITLE
Increase contrast between validators and UNL pills on the ledger card

### ISSUE THREAD

**Issue by bugsbunnies** [ripple/explorer#229]
Increase contrast between validators and UNL pills (for better accessibility), also highlight UNL instead of other validators. 

Proposed design: 
UNL pills - Primary white
Other validator pills - Gray500
<img width="364" alt="Screen Shot 2022-08-10 at 9 33 08 AM" src="https://user-images.githubusercontent.com/39572746/183964433-6ff1bf12-7c88-46da-9439-6aef3dd004f7.png">

Existing:
<img width="338" alt="Screen Shot 2022-08-10 at 9 32 50 AM" src="https://user-images.githubusercontent.com/39572746/183964458-ab55d786-8dfe-4586-8c2e-f40bc50d45ee.png">

**Comment by ckniffen** [comment]
@bugsbunnies What should the colors be when one is selcted?

**Comment by bugsbunnies** [comment]
> 

Primary green when selected @ckniffen thank you!

**Comment by ckniffen** [comment]
@bugsbunnies This is what I was referring to.  The non selected validators have a different color when one is selected.

###Here is an example of this

![Screen Shot 2022-09-06 at 5 54 37 PM](https://user-images.githubusercontent.com/464895/188754283-23fb0593-a578-4f60-9c3d-11ea3a650cf2.png)

**Comment by bugsbunnies** [comment]
Thanks @ckniffen, can we still apply the { opacity: .4 } to the new colors?

**Comment by ckniffen** [comment]
Yeah.  Just wanted to confirm.

**Comment by ckniffen** [comment]
Completed by #535
