### ISSUE TITLE
Cleanup duplicate "section" classes

### ISSUE THREAD

**Issue by shawnxie999** [ripple/explorer#234]
1. Remove the `section` class selector from `NFTHeader`, `TokenHeader` and `AccountHeader`. Put this class into a shared file. However there is a behavior, that, when we remove all of the `section`, the tab inside Account will be left aligned(will need do more investigation and make sure its not occurring when doing the cleaup)
![image](https://user-images.githubusercontent.com/35279399/184425521-c8c1745e-1117-44a4-b032-80793493af0c.png)

2. Rename the `section` under `detailTab.scss `, and all of its occurances

**Comment by ckniffen** [comment]
Fixed in #219

**Comment by shawnxie999** [comment]
Reponed, didnt fix it
