### ISSUE TITLE
Server version chart

### ISSUE THREAD

**Issue by mDuo13** [ripple/explorer#25]
Per @crypticrabbit ( https://github.com/XRPLF/xrpl-dev-portal/issues/1161 )

> I think it would be useful (for things like amendment voting decisions) to have a chart showing what proportion of the network is running a given version of rippled on the livenet.xrpl.org/network page.
>
> Something similar to the chart in the top right of this page: https://xrpcharts.ripple.com/#/topology
>
> While the chart on the ripple.com page appears accurate, I think there are still multiple reasons (convenience, ensuring data accuracy, independent data, etc.) that having the chart on xrpl.org would be beneficial.
>
> Cheers!

**Comment by intelliot** [comment]
The chart on xrpcharts is no longer updated, making this request more urgent. Also, xrpscan shows validator versions, but not the versions of normal (non-validator) nodes on the network.
