### ISSUE TITLE
Add ability to connect to insecure rippled and clio servers

### ISSUE THREAD

**Issue by ckniffen** [ripple/explorer#258]
In an effort to make local development easier there should be a simple way to connect to insecure/local servers instead of directly editing code.

Right now `wss` is the implied protocol that must be used when defining [REACT_APP_RIPPLED_HOST](https://github.com/ripple/explorer/blob/staging/.env.example#L5) and [REACT_APP_P2P_RIPPLED_HOST](https://github.com/ripple/explorer/blob/staging/.env.example#L7). These are used [here](https://github.com/ripple/explorer/blob/staging/src/containers/App/App.js#L29-L47).  

One option is to make the host environment variable values incorporate the protocol.  The other is to have a new environment variable that is used to swap between using `wss/https` and `ws/http`.

**Comment by rashidmya** [comment]
can I try doing this?

**Comment by ckniffen** [comment]
> can I try doing this?

Sure thing.  Fork the repo and when you are done create a pull request.

**Comment by ckniffen** [comment]
@rashidmya also feel free to ask any questions in the ticket.

**Comment by rashidmya** [comment]
> One option is to make the host environment variable values incorporate the protocol. 
Is this what you meant? #266

If not, maybe i can just add a new environment variable to swap between secure and insecure connections

**Comment by ckniffen** [comment]
REACT_APP_ENVIRONMENT is used to distinguish the various networks such as

- https://livenet.xrpl.org/
- https://testnet.xrpl.org/
- https://devnet.xrpl.org/
- https://nft-devnet.xrpl.org/
- https://sidechain.xrpl.org/

This task is for a scenario like "As a user I want to connect to a testnet rippled or clio node that does not have ssl enabled" Usually this is done to hit a local server or one on another machine in the same private network. In that scenario the `REACT_APP_ENVIRONMENT === 'testnet'` and I want it to use `ws`.  However in production for https://testnet.xrpl.org/ `REACT_APP_ENVIRONMENT === 'testnet'` will also be true but we want to use `wss`.  This makes `REACT_APP_ENVIRONMENT` not a good variable to base this off of.

Additionally for local development I typically point to a production rippled node so relying on `NODE_ENV` is not feasible either.

**Comment by rashidmya** [comment]
> Additionally for local development I typically point to a production rippled node so relying on `NODE_ENV` is not feasible either.

so an environment variable to switch between secure and insecure connections would be a solutions to this i guess

**Comment by ckniffen** [comment]
Yes or force all host names in env to explicitly include the protocol.

**Comment by rashidmya** [comment]
I went with the approach of having a new env variable `REACT_APP_RIPPLED_SECURE` to switch between `ws` and `wss`

thoughts on changes?

**Comment by mvadari** [comment]
For reference (fixes have been tried before but failed in prod): https://github.com/ripple/explorer/pull/106

I don't like the idea of having a new env variable for this - it clutters up the env vars, and we already have a lot.

**Comment by rashidmya** [comment]
> I don't like the idea of having a new env variable for this - it clutters up the env vars, and we already have a lot.

we can force all host names in env to include the protocol as @ckniffen suggested

**Comment by mvadari** [comment]
> we can force all host names in env to include the protocol as @ckniffen suggested

I'm not quite sure what the utility of that is. The live version of the Explorer only supports `wss` due to CORS, so it feels like that will just make everything more complex in the deployed version for no reason.
