### ISSUE TITLE
Update footer to reflect links on xrpl.org 

### ISSUE THREAD

**Issue by ckniffen** [ripple/explorer#262]
Recently the footer links were updated on xrpl.org.

The footer needs to be updated to reflect the new groupings and use a subset of the links.

@mduo13 Which do you think should be excluded?

**Comment by mDuo13** [comment]
I think it's OK if you copy the entire footer verbatim. Alternatively, you could make a really simple subset of the following:

- [XRPL Overview](https://xrpl.org/xrp-ledger-overview.html)
- [Documentation](https://xrpl.org/docs.html)
- [Community](https://xrpl.org/contribute.html)

**Comment by ckniffen** [comment]
Fixed by #623
