### ISSUE TITLE
Show for which amendments is validator voting

### ISSUE THREAD

**Issue by golobitch** [ripple/explorer#363]
To me personaly, validators screen is good enough only for checking to see if somebody is on nUNL list and what version is each validator using.

I would like to see also amendments for which validator is voting and amendment details. 
For amendment details, there is no need to implement additional screen in explorer. Just a link to documentation would suffice (for example: https://xrpl.org/known-amendments.html#expandedsignerlist)

More that I am thinking about amendment details, the more I believe that there should be separate screen. There can be link to the documentation on that page, but that page should also show where we are with the votes (do we have more that 80%), whos is voting for and who against, what is the default vote for this amendment, etc.

**Comment by mvadari** [comment]
Fixed by #830
