### ISSUE TITLE
Update to `node@18`

### ISSUE THREAD

**Issue by ckniffen** [ripple/explorer#382]
Currently we are using Node 14.  Node 18 will be a LTS and supported through April 2025.

**Comment by lathanbritz** [comment]
<img width="570" alt="Screen Shot 2022-12-07 at 00 28 13" src="https://user-images.githubusercontent.com/508629/206081193-b33f170a-0757-4da8-97ee-9257feea349b.png">
node 17 as well fails.....

**Comment by mvadari** [comment]
> node 17 as well fails.....

That's an artificial block - you can adjust the engines in package.json to get around that.
