### ISSUE TITLE
Offer Create tx displays wrong buy/sell pair

### ISSUE THREAD

**Issue by mrosendin** [ripple/explorer#43]
In this screenshot, it says xrp was bought / phi was sold
![Screen Shot 2021-12-29 at 9 10 27 AM](https://user-images.githubusercontent.com/3401412/147686882-a847b4ea-2784-4157-b7cb-edfb1a6a38d0.png)

in the detail view it says phi was bought / xrp sold
![Screen Shot 2021-12-29 at 9 10 42 AM](https://user-images.githubusercontent.com/3401412/147686978-b0fdde87-3be6-48c7-92b1-feff9751298d.png)

the 2nd screenshot is correct, the first one displays the currencies flipped the wrong way.

https://testnet.xrpl.org/accounts/rfc9vxWtSFeWtpD9N3qsn4YHqZ7Ph2pZvN

**Comment by JST5000** [comment]
Thanks for pointing this out! (Sorry I forgot to reply when I read this earlier)
