### ISSUE TITLE
fix: empty validators on Network's Validators page.

### ISSUE THREAD

**Issue by pdp2121** [ripple/explorer#451]
There are a few empty validators that has no data and cause the validators table to flicker. Need to investigate where they come from and remove them.

![Screenshot 2022-11-08 at 4 02 19 PM](https://user-images.githubusercontent.com/71317875/200675745-bf48431c-f4d6-44bb-852d-f84450ccde81.png)

**Comment by ckniffen** [comment]
Fixed by #467
