### ISSUE TITLE
Email hash may not be ever displayed in account header

### ISSUE THREAD

**Issue by shawnxie999** [ripple/explorer#476]
Email hash may not be ever shown in account header.
Props declares email hash as snake case in [AccountHeader](https://github.com/ripple/explorer/blob/8ac4e416097d03b6ab2faad44390d0a28f6259e6/src/containers/Accounts/AccountHeader/index.js#L355). But inside [formatAccountInfo](https://github.com/ripple/explorer/blob/8ac4e416097d03b6ab2faad44390d0a28f6259e6/src/rippled/lib/utils.js#L62), email hash is returned in camelcase.

Worth looking in having test cases

**Comment by Sash002** [comment]
To add an emailHash feature to the AccountHeader component, we can add a new emailHash property to the data object and define its type in the propTypes.
