### ISSUE TITLE
The parser for `NFTokenAcceptOffer` will sometimes return an incorrect address as buyer/accepter

### ISSUE THREAD

**Issue by will2022** [ripple/explorer#492]
I found an example where the parser for NFTokenAcceptOffer returns the wrong buyer: https://livenet.xrpl.org/transactions/E6CE3C3C554BA01891A9D12E89062C34BBEA6282CF8AA4D9AF8BF7D0E7D26B7D/simple

![image](https://user-images.githubusercontent.com/12783306/205526253-9452cc7e-11f5-4ed9-91c3-68973ab50dfc.png)

Looking at the detailed view it's possible to see who the real buyer is
![image](https://user-images.githubusercontent.com/12783306/205526268-0ecc6fc2-5494-4c51-92fe-a1f1a94ca504.png)

The ownership history shown on [Bithomp](https://bithomp.com/explorer/00081B581189F5687DBB7516339D6CCB5593D96622AD82DF08CFDA8600000A17) does also specify the actual buyer

I've quickly looked at `src/containers/shared/components/Transaction/NFTokenAcceptOffer/parser.ts`. It seems like the accepter maybe should be defined as `const accepter = acceptedOfferNode.Destination ? acceptedOfferNode.Destination : tx.Account;`.

**Comment by will2022** [comment]
Fixed by https://github.com/ripple/explorer/pull/493

**Comment by will2022** [comment]
The #493 pull request isn't gonna fix this.

The `AffectedNodes` array has two `DeletedNode` objects. Both with the `LedgerEntryType` set to `NFTokenOffer`. It's the second one that has the correct NFT owner, but it's the first one that gets chosen.
![image](https://user-images.githubusercontent.com/12783306/205650983-55cad7a8-4f8e-44f5-a1f1-a5fed00509d3.png)

**Comment by shawnxie999** [comment]
> The #493 pull request isn't gonna fix this.
> 
> The `AffectedNodes` array has two `DeletedNode` objects. Both with the `LedgerEntryType` set to `NFTokenOffer`. It's the second one that has the correct NFT owner, but it's the first one that gets chosen.
> 
> For privacy-ish reasons, I'm attaching an image so searching for their wallet on Google won't link to this issue ![image](https://user-images.githubusercontent.com/12783306/205650983-55cad7a8-4f8e-44f5-a1f1-a5fed00509d3.png)

Thanks we will take a look

**Comment by mvadari** [comment]
The problem is that the parser only takes the first accepted offer, but in a brokered transfer, two offers are accepted, and the account submitting the transaction is neither the seller nor the buyer. The `tx.Account` is the broker (which should probably also be specified, but separately). 

So a fix would probably be to find all the accepted offer nodes (instead of just the first), make sure the number of nodes matches the number of offers, figure out which is the sell offer and which is the buy offer, and use that to determine the buyer and seller.

**Comment by shawnxie999** [comment]
@mvadari @ckniffen @will2022 I have opened a PR that would choose the node without the `Destination` field to fetch the buyer in brokered mode. Im open to discuss the correctness of this solution and whether there is a better way
