### ISSUE TITLE
Support other currency/issuer formats for search

### ISSUE THREAD

**Issue by ckniffen** [ripple/explorer#624]
The search currently supports `{currencyCode}.{issuer}` we should also support `{currencyCode}:{issuer}`, `{currencyCode}+{issuer}`, and `{currencyCode}-{issuer}`.

These are formats used by some many dexs.

https://gatehub.net/markets/XRP/EUR+rhub8VRN55s94qWKDv6jmDy1pUykJzF3wq
https://xdex.com/tokens/SOLO:rsoLo2S1kiGeCcn6hCUXVrCpGMWLrRrLZz
https://sologenic.org/trade?network=mainnet&market=534F4C4F00000000000000000000000000000000%2BrsoLo2S1kiGeCcn6hCUXVrCpGMWLrRrLZz%2FXRP
https://xpmarket.com/dex/XRP/USD-rvYAfWj5gh67oV6fW32ZzP3Aw4Eubs59B

**Comment by intelliot** [comment]
For reference, could we link (here in this issue) examples of explorers and dexs that use the aforementioned formats?

**Comment by ckniffen** [comment]
fixed by #762
