### ISSUE TITLE
Indicating when an account does not exist

### ISSUE THREAD

**Issue by develoQ** [ripple/explorer#661]
It should be possible to clearly indicate that an account does not exist when it does not exist.

The current error message makes me think that there is some error on the server side.

https://livenet.xrpl.org/accounts/rndpDXFdkgR4EmDXnPgC36VxRBbjqu8rHP

<img width="1470" alt="image" src="https://user-images.githubusercontent.com/69445828/230261189-3bd40040-5248-476a-b1f7-cd883c294e47.png">

**Comment by ckniffen** [comment]
For that url I am getting this.  
![Screenshot_20230405-220009](https://user-images.githubusercontent.com/464895/230261642-c13e217d-8be9-4f1f-894e-1167f2129eac.png)

**Comment by develoQ** [comment]
I checked and Chrome is showing Account Not Found.
In Safari it is the error I noted.

It contains a little Japanese, but the error is as follows.

```
[Error] TypeError: Error.captureStackTrace is not a function. (In 'Error.captureStackTrace(this,this.constructor)', 'Error.captureStackTrace' is undefined)
gt — index-49a35023.js:150:76995
（anonymous関数） — index-49a35023.js:150:79134

    onError (index-49a35023.js:79:41594)
    u (index-49a35023.js:79:35275)
    （anonymous関数） (index-49a35023.js:79:35957)
```

**Comment by ckniffen** [comment]
This is caused by Firefox and Safari not supporting `Error.captureStackTrace`.  This code has been there for at least 5 years.  After I fix this you will see more context aware error messages throughout the site.
