### ISSUE TITLE
Handle loading of the `/detailed` tab in transactions better

### ISSUE THREAD

**Issue by mvadari** [ripple/explorer#71]
The transaction at https://livenet.xrpl.org/transactions/9BE43A0058FF4C358015CD89CE754AFEF201A6FF3D7E2C868B8C7E61DB00BD68 takes forever to load the `/detailed` tab, because there are over 2500 affected nodes. While this page processes all the nodes, it just shows a blank page. There should be a better loading sign.

**Comment by intelliot** [comment]
@mvadari @ckniffen the page seems to load ok now. What more is there to do for this issue?

**Comment by mvadari** [comment]
Yeah, I think this was resolved by #132

**Comment by ckniffen** [comment]
It still loads slower than it should but I am okay closing it.

I have code somewhere that renders it in increments instead of all at once.  Much lower priority now.

**Comment by intelliot** [comment]
Cool. We can still improve the speed / efficiency / progressive-loading, but since it's low priority, I'll close this issue for now. Feel free to reopen or create a new one when the time comes. Thanks!
