### ISSUE TITLE
Handle protocols inside domain fields

### ISSUE THREAD

**Issue by ckniffen** [ripple/explorer#714]
Some accounts such as issuers of NFTs put fully formed urls in the domain field.  Since we prepend "https://" to the value of that field always this creates an invalid URI.  We should only add "https://" if we do not detect a protocol.

Example: https://livenet.xrpl.org/accounts/r481fwr9G6GqJsnDTRanb9wicGjFf3rfgp/transactions
Component to be updated: https://github.com/ripple/explorer/blob/staging/src/containers/shared/components/DomainLink.tsx

**Comment by sohammk08** [comment]
Hi there! I'm interested in working on this issue. Would it be possible to assign this to me?

**Comment by ckniffen** [comment]
We only assign to main contributors.  You can go ahead and submit a PR though.

**Comment by sohammk08** [comment]
Thanks for commenting in such a short time. I'll start working on it :)

**Comment by sohammk08** [comment]
I tried solving the issue. I require your feedback on the same.
Check it out here:

[https://github.com/ripple/explorer/pull/856](url)
