### ISSUE TITLE
Format currency hex values on AMM account pages

### ISSUE THREAD

**Issue by ckniffen** [ripple/explorer#717]
The currency codes shown for balances need to take into account hex based currencies.  Using the `<Currency>` component should fix it.

https://amm-devnet.xrpl.org/accounts/rpwtoDgigJj2rEfbWDghiLXHdm1zSwHaBD

![Monosnap XRPL Explorer | rpwtoDgigJj2  2023-05-26 17-32-47](https://github.com/ripple/explorer/assets/464895/3795f0b4-d762-4cef-b597-8bb63cbbb16d)

**Comment by tarunsamanta2k20** [comment]
I'd like to work on it.
