### ISSUE TITLE
Raw Txn data fields missing

### ISSUE THREAD

**Issue by develoQ** [ripple/explorer#786]
The `ledger_index`, `hash`, and `meta` fields in the `tx` field of the transaction raw data are not set.

Based on the reference these should be included within the tx field.
https://xrpl.org/tx.html

https://livenet.xrpl.org/transactions/F48176B53B69D6CDC3D0E3D6A513B555E166E4CC6D3738F78A40B7CB08D5E4C5/raw

<img width="623" alt="スクリーンショット 2023-07-23 21 01 43" src="https://github.com/ripple/explorer/assets/69445828/953f30dd-f637-4c13-8ace-593c0c98a1b3">

**Comment by justinr1234** [comment]
https://bithomp.com/explorer/F48176B53B69D6CDC3D0E3D6A513B555E166E4CC6D3738F78A40B7CB08D5E4C5

**Comment by ckniffen** [comment]
@develoQ you are correct. Raw does not equal to response from tx. This work will be done as part of #358.
