### ISSUE TITLE
Fix Uppercased address

### ISSUE THREAD

**Issue by develoQ** [ripple/explorer#800]
XRPL account addresses are case sensitive and should not be displayed with the address in all uppercase.

Following `USD.RG2M`.

https://amm-devnet.xrpl.org/accounts/rNJNwK5EjaKnQYJVGTgcrHDQ5fPXxw9sWK

![スクリーンショット 2023-08-02 15 12 16](https://github.com/ripple/explorer/assets/69445828/3ff7dafa-72da-4286-9468-fc9f3729f140)

**Comment by mdazad1508** [comment]
is this issue closed?

**Comment by ckniffen** [comment]
No. It is still open.  You will need the changes in #808 to work on it.

**Comment by develoQ** [comment]
AMM-Devnet has been reset and cannot be verified by the above link.

This is the currently active link.

https://amm-devnet.xrpl.org/accounts/rfcaLudvZEfr6oHKCkHtuSwXxcrRE6rsoi
