### ISSUE TITLE
Don't translate language names

### ISSUE THREAD

**Issue by develoQ** [ripple/explorer#807]
`language_en-US`, `language_ja-JP` and `language_fr-FR` should be provided in English without conversion to other languages.

If users change to a language they are not familiar with, they may not be able to return to the original language.

**Comment by mdazad1508** [comment]
could you give more insight of the issue?

**Comment by develoQ** [comment]
For example, if an English speaker mistakenly selects Japanese, he or she will want to revert to the original English.

In such a case, the English speaker does not know which option to choose.

**Comment by mdazad1508** [comment]
Got it . could you please review my PR.
* #809
