### ISSUE TITLE
Add Xrplorer's forensics services

### ISSUE THREAD

**Issue by mDuo13** [ripple/explorer#87]
Original issue: https://github.com/XRPLF/xrpl-dev-portal/issues/1293
Original reporter: @wojake

> I believe adding Xrplorer's forensic services to the explorer would greatly reduce the amount of scammed victims, it would also increase the XRP Ledger's transparency.
>
> When someone searches for an address (activated or not), refer to Xrplorer's forensic DB which contains a list of reported accounts and display something similar to this:
> ![Mockup screenshot](https://user-images.githubusercontent.com/87929946/149080324-24c859e5-7eec-4080-96b3-8411efe31a75.png)
> 
> I've suggested this to xrpscan.com and would hope to see such thing being implemented in xrpl.org, thank you.
> Links:
>
> -  https://xrplorer.com/
> -  https://xrplorer.com/products/advisorylist

**Comment by ckniffen** [comment]
Another suggestion is to collapse the memo field for transactions performed by a spam account with a message saying they are spammers.

**Comment by wojake** [comment]
I disagree, the explorer should do what it does best, displaying data in a complete and clean format. A small notice is enough if an account is flagged by the forensics service.

**Comment by mvadari** [comment]
Looks like the Xrplorer's forensic service has been deprecated, so we'd need to find another service.

**Comment by Silkjaer** [comment]
The forensics API (both case reporting and serving) is still hosted by xrplorer at this moment, but is generally absorbed by the XRPLF. The API was used by several explorers in the past, but we made a decision to recall use on explorers at it is of larger benefit to the actual scammers, than victims. It will invite scraping activities, monitoring for whether accounts are flagged or not, new attempts to try and circumvent flagging etc.

IMO explorers should report content as is. Potentially adding warnings based on their own logic (e.g. if it's a high frequency sender of memos).

**Comment by intelliot** [comment]
per Silkjaer, there is no need to integrate with xrplorer. Thanks!
