### ISSUE TITLE
Replace the logic in `amendmentUtils.ts` with validator-history-service API for `EnableAmendment` transaction

### ISSUE THREAD

**Issue by pdp2121** [ripple/explorer#894]
The logic in this file to populate data for `EnableAmendment` transactions:
https://github.com/ripple/explorer/blob/staging/src/containers/shared/amendmentUtils.ts

can be now replaced with the validator-history-service new API:
https://data.xrpl.org/v1/network/amendment/info/{amendment id/name}

For example:
https://data.xrpl.org/v1/network/amendment/info/8CC0774A3BF66D1D22E76BBDA8E8A232E6B6313834301B3B23E8601196AE6455

**Comment by nick2432** [comment]
can i work on this?

**Comment by mvadari** [comment]
> can i work on this?

@nick2432 sure!

**Comment by pdp2121** [comment]
@nick2432 just want to check in and see if you need help on this. Thanks!

**Comment by pdp2121** [comment]
Closed this one and open the following as an alternative (better) solution: https://github.com/ripple/explorer/issues/1001
